### PR TITLE
Sflowers51 introduction meme

### PR DESCRIPTION
**Pull request by sflowers51**

### CODE REVIEW

**Comment by sflowers51** [comment]
I am not entirely sure how to fix this issue right now.

**Comment by Soyokaze-42** [comment]
What are you trying to do?

**Comment by sflowers51** [comment]
I misunderstood what was happening for chapter 4 and I thought we are going
to updated the introduction thing. I thought I was going to merge but I was
wrong. Before the PR, it was good and ready to be reviewed.

**Comment by Soyokaze-42** [comment]
Ok. I think the only thing to do is close this PR.

**Pull request closed without merging**
