### PR TITLE
dannyrich24-introduction-meme

### PR DESCRIPTION
**Pull request by Soyokaze-42**
dannyrich24's meme for introduction

### CODE REVIEW

**Review by dannyrich24 — APPROVED** [review]
WOW! So good!

**Review by PierceKlugs — APPROVED** [review]
Cool

**Review by GreeneGunnar14 — APPROVED** [review]
Good meme. Made me laugh when he showed me before class.

**Comment by Soyokaze-42** [comment]
I don't know any operating system geeks who are going to make that statement... One of the functions of an operating system is as a resource manager, but there are lots of other types of resource managers out there. Thinking of an OS as a resource manager is a great way to learn what it does.

**Pull request merged**
