### PR TITLE
allisoncwalker-the-process-meme

### PR DESCRIPTION
**Pull request by Soyokaze-42**
allisoncwalker's meme for the-process

### CODE REVIEW

**Comment by Soyokaze-42** [comment]
We are going to do something a little different with the teams, so the author for this should be allison. So, please delete the Women author file and fix the author in the meme's front matter.

**Comment by allisoncwalker** [comment]
ok

>

**Comment by Soyokaze-42** [comment]
@allisoncwalker why did you close this PR? It looks like you had a meme and your post ready to merge to me...

**Comment by Soyokaze-42** [comment]
I see a little bonus fix in this PR for Allison's introduction meme. That is fine :)

**Pull request merged**
